In [34]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [35]:
df = pd.read_csv('Cancer.csv')
df

   gender  age  smoking cancer
0    male    23     yes     no
1    male    55      no     no
2  female    34     yes    yes
3    male    18     yes    yes
4    male    52      no    yes
5  female    25      no     no
6    male    56     yes     no
7    male    30     yes    yes
8  female    45      no    yes

In [36]:
label_encoder = LabelEncoder()
print(label_encoder)

LabelEncoder()

In [37]:
df['smoking'] = label_encoder.fit_transform(df['smoking'])
df['gender'] = label_encoder.fit_transform(df['gender'])
df['cancer'] = label_encoder.fit_transform(df['cancer'])

In [38]:
df

   gender  age   smoking  cancer
0       1    23        1       0
1       1    55        0       0
2       0    34        1       1
3       1    18        1       1
4       1    52        0       1
5       0    25        0       0
6       1    56        1       0
7       1    30        1       1
8       0    45        0       1

In [39]:
X = df.drop('cancer', axis=1)
print(X)
y = df['cancer']
print(y)

   gender  age   smoking
0       1    23        1
1       1    55        0
2       0    34        1
3       1    18        1
4       1    52        0
5       0    25        0
6       1    56        1
7       1    30        1
8       0    45        0
0    0
1    0
2    1
3    1
4    1
5    0
6    0
7    1
8    1
Name: cancer, dtype: int64

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [45]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [46]:
a=model.predict([[0,34,1]])
#a = np.array(model.predict([[0,34,1]]))

C:\Users\Student\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [47]:
a

array([1])

In [48]:
original_data = label_encoder.inverse_transform(a)

In [49]:
original_data

array(['yes'], dtype=object)